GET http://localhost:8000

### -------------------register----------------
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "Ezra",
    "email": "partner@gmail.com",
    "contact": "2134567890",
    "address": "123 Main St",
    "role": "partner",
    "company_name": "Company",
    "company_address": "123 Main St",
    "company_contact": "2134567890",
    "company_email": "company@gmail.com",
    "password": "password"
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "Ezra",
    "email": "partner@gmail.com",
    "contact": "2134567890",
    "address": "123 Main St",
    "role": "user",
    "password": "password"
}

### -------------------------login------------------
POST  http://localhost:8000/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "password"
}

### -------------------------users------------------
GET http://localhost:8000/users

###
GET http://localhost:8000/users/3

###
PUT http://localhost:8000/user/update/7
Content-Type: application/json

{
    "email": "example@gmail.com",
    "role": "user"
}

###
DELETE http://localhost:8000/user/delete/7

### -------------------------partners------------------
GET http://localhost:8000/partners

###
GET http://localhost:8000/partners/1

###
PUT http://localhost:8000/partner/update/1
Content-Type: application/json

{
    "company_contact": "209384837849"
}

###
DELETE http://localhost:8000/partner/delete/7

### -------------------------surveys------------------
GET http://localhost:8000/surveys

###
GET http://localhost:8000/surveys/1

###
POST http://localhost:8000/survey/create
Content-Type: application/json

{
    "created_by": 1,
    "title": "Electronics",
    "description": "Electronic review",
    "status": "active",
    "reward": 250.00
}

###
PUT http://localhost:8000/survey/update/1
Content-Type: application/json

{
    "reward": 255.00
}

###
DELETE http://localhost:8000/survey/delete/2