GET http://localhost:8000

### -------------------register----------------
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "Ezra",
    "email": "partner@gmail.com",
    "contact": "2134567890",
    "address": "123 Main St",
    "role": "partner",
    "company_name": "Company",
    "company_address": "123 Main St",
    "company_contact": "2134567890",
    "company_email": "company@gmail.com",
    "password": "password"
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
    "full_name": "Ezra",
    "email": "partner@gmail.com",
    "contact": "2134567890",
    "address": "123 Main St",
    "role": "user",
    "password": "password"
}

### -------------------------login------------------
POST  http://localhost:8000/login
Content-Type: application/json

{
    "email": "partner@gmail.com",
    "password": "password"
}

### -------------------------users------------------
GET http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbGlzaGFraXBsYW5nYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoxLCJleHAiOjE3Mjc1NjI3MjZ9.RlWwgg1ttQDOTNw_4PlEhQtaWdVyEHL2AdCRJfj0CtA

###
GET http://localhost:8000/users/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6NywiZXhwIjoxNzI3NTYyODAyfQ.M6TV9R1898Cht68OtvFAvU39AqiehD_gHsOXhAvpUUQ

###
PUT http://localhost:8000/user/update/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleGFtcGxlMUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInVzZXJfaWQiOjYsImV4cCI6MTcyNzU2MjkzOX0._Rsy3PmgI_FBn1WHqE8ysYKr2Zuw8arHlq_l_-qe57s
Content-Type: application/json

{
    "email": "example@gmail.com"
}

###
DELETE http://localhost:8000/user/delete/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleGFtcGxlQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6MywiZXhwIjoxNzI3NTYwNzc5fQ.RRRnD2e4-LIKHWB87BZ6d7lIa8kkOBGqePAeyH4lWao

###
GET http://localhost:8000/user/partner/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbGlzaGFraXBsYW5nYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoxLCJleHAiOjE3Mjc1NjMwMjN9.UUSjlJhYW5XTEYngFatib0hw1GzG010AT0cRBsk-tWQ

###
GET http://localhost:8000/users/surveys/payments/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6NywiZXhwIjoxNzI3NTYzMjU0fQ.3bQzN68dpD9mZ93-Vs7x9piaWv_kD8GSdLoWUkFzj-8

###
GET http://localhost:8000/users/messages/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6NywiZXhwIjoxNzI3NTYzMjU0fQ.3bQzN68dpD9mZ93-Vs7x9piaWv_kD8GSdLoWUkFzj-8

###
GET http://localhost:8000/users/partners/requests/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6NywiZXhwIjoxNzI3NTYzMjU0fQ.3bQzN68dpD9mZ93-Vs7x9piaWv_kD8GSdLoWUkFzj-8

###
GET http://localhost:8000/users/support/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXJ0bmVyQGdtYWlsLmNvbSIsInJvbGUiOiJwYXJ0bmVyIiwidXNlcl9pZCI6NywiZXhwIjoxNzI3NTYzMjU0fQ.3bQzN68dpD9mZ93-Vs7x9piaWv_kD8GSdLoWUkFzj-8

### -------------------------partners------------------
GET http://localhost:8000/partners

###
GET http://localhost:8000/partners/1

###
PUT http://localhost:8000/partner/update/1
Content-Type: application/json

{
    "company_contact": "209384837849"
}

###
DELETE http://localhost:8000/partner/delete/7

### -------------------------surveys------------------
GET http://localhost:8000/surveys

###
GET http://localhost:8000/surveys/1

###
POST http://localhost:8000/survey/create
Content-Type: application/json

{
    "created_by": 1,
    "title": "Electronics",
    "description": "Electronic review",
    "status": "active",
    "reward": 250.00
}

###
PUT http://localhost:8000/survey/update/1
Content-Type: application/json

{
    "reward": 255.00
}

###
DELETE http://localhost:8000/survey/delete/2

###
GET http://localhost:8000/surveys/quiz/1

###
GET http://localhost:8000/surveys/payments/3

###
GET http://localhost:8000/survey/results/1

### -------------------------questions------------------
GET http://localhost:8000/questions

###
GET http://localhost:8000/questions/1

###
POST http://localhost:8000/questions/create
Content-Type: application/json

{
    "survey_id": 1,
    "question_text": "What is your favorite color?",
    "question_type": "multiple_choice"
}

###
PUT http://localhost:8000/questions/update/1
Content-Type: application/json

{
    "question_type": "text"
}

###
DELETE http://localhost:8000/questions/delete/2

### -------------------------choices------------------
GET http://localhost:8000/choices

###
GET http://localhost:8000/choices/1

###
POST http://localhost:8000/choices/create
Content-Type: application/json

{
    "question_id": 1,
    "choice_text": "Yes"
}

###
PUT http://localhost:8000/choices/update/1
Content-Type: application/json

{
    "choice_text": "No"
}

###
DELETE http://localhost:8000/choices/delete/2

### -------------------------answers------------------
GET http://localhost:8000/answers

###
GET http://localhost:8000/answers/1

###
POST http://localhost:8000/answers/create
Content-Type: application/json

{
    "question_id": 1,
    "choice_id": 1,
    "user_id": 1,
    "answer_text": "Recommended"
}

###
PUT http://localhost:8000/answers/update/2
Content-Type: application/json

{
    "answer_text": "Recommended to young"
}

###
DELETE http://localhost:8000/answers/delete/2

### -------------------------results------------------
GET http://localhost:8000/results

###
GET http://localhost:8000/results/1

###
POST http://localhost:8000/results/create
Content-Type: application/json

{
    "survey_id": 1,
    "submitted_by": 7,
    "result_data": {
        "question_1": "Option A",
        "question_2": "Option C",
        "question_3": "Free text response"
    }
}

###
PUT http://localhost:8000/results/update/2
Content-Type: application/json

{
    "submitted_by": 7
}

###
DELETE http://localhost:8000/results/delete/2


### -------------------------payments------------------
GET http://localhost:8000/payments

###
GET http://localhost:8000/payments/1

###
POST http://localhost:8000/payments/create
Content-Type: application/json

{
    "user_id": 1,
    "amount": 250.00,
    "payment_status": "pending",
    "payment_method": "Mpesa",
    "transaction_id": "siqus2jf3nd"
}

###
PUT http://localhost:8000/payments/update/2
Content-Type: application/json

{
    "payment_method": "cash"
}

###
DELETE http://localhost:8000/payments/delete/2

### -------------------------messages------------------
GET http://localhost:8000/messages

###
GET http://localhost:8000/messages/1

###
POST http://localhost:8000/messages/create
Content-Type: application/json

{
    "from_user_id": 7,
    "to_user_id": 1,
    "subject": "payment issue",
    "message_body": "not received my payment",
    "status": "read"
}

###
PUT http://localhost:8000/messages/update/2
Content-Type: application/json

{
    "status": "sent"
}

###
DELETE http://localhost:8000/messages/delete/2

### -------------------------requests------------------
GET http://localhost:8000/requests

###
GET http://localhost:8000/requests/1

###
POST http://localhost:8000/requests/create
Content-Type: application/json

{
    "client_partner_id": 1,
    "requested_survey_title": "Product review",
    "status": "pending"
}

###
PUT http://localhost:8000/requests/update/2
Content-Type: application/json

{
    "status": "approved"
}

###
DELETE http://localhost:8000/requests/delete/2

### -------------------------audits------------------
GET http://localhost:8000/audit-logs

###
GET http://localhost:8000/audit-logs/1

###
POST http://localhost:8000/audit-logs/create
Content-Type: application/json

{
    "user_id": 7,
    "action": "Quality",
    "description": "good quality"
}

###
PUT http://localhost:8000/audit-logs/update/2
Content-Type: application/json

{
    "description": "needs some analysis"
}

###
DELETE http://localhost:8000/audit-logs/delete/2

### -------------------------support------------------
GET http://localhost:8000/support-tickets

###
GET http://localhost:8000/support-tickets/1

###
POST http://localhost:8000/support-tickets/create
Content-Type: application/json

{
    "user_id": 6,
    "subject": "Surveys",
    "description": "Survey unavailable",
    "status": "open"
}

###
PUT http://localhost:8000/support-tickets/update/2
Content-Type: application/json

{
    "status": "in_progress",
    "resolved_by": 1
}

###
DELETE http://localhost:8000/support-tickets/delete/2